### PR TITLE
Use Expo instead of raw React Native

### PR DESCRIPTION
**Pull request by rmccue**
Was having a play around with this. Far from a working PR, but opening one so I have it somewhere.

### CODE REVIEW

**Comment by rmccue** [comment]
Got it working @joehoyle. :)

To test it out:

1. Clone down the repo somewhere completely new
2. Run `npm install` and `npm start`
4. Install the Expo app on your phone
5. Use the Camera app to scan the QR code

No native compiling required at all. 💥

**Comment by rmccue** [comment]
Note that the callback URL for OAuth will need to change; I'm using the HM site to test, so edited the URL [on the app](https://humanmade.com/wp-admin/users.php?page=rest-oauth1-apps&action=edit&id=7247&did_action=edit). The dev console will give you a callback URL, so when you get the callback URL error, update it there and refresh.

**Comment by joehoyle** [comment]
@rmccue where do I get the QR code from? `npm start` doesn't appear to show anythign to do with that.

**Comment by rmccue** [comment]
@joehoyle You should see the following in your terminal:

Screen Shot 2019-05-06 at 12 31 09

Also, if you open the devtools URL (port 19002 usually), you should see this:

Screenshot_2019-05-06 (2) Vienna on Expo Developer Tools

Alternatively, log in to an expo.io account and it should appear in your Expo app automatically.

**Comment by joehoyle** [comment]
Nice, working! Ready to merge IMO

**Pull request merged**
