### PR TITLE
Add TinyMCE

### PR DESCRIPTION
**Pull request by rmccue**
Main content screen | Post properties modal
-- | --
image | image

Needs further work still.

Requires SF Symbols icon font. I can't work out a way to detect if the font file exists and conditionally load it yet though. 🤔

### CODE REVIEW

**Comment by joehoyle** [comment]
Hmm how do I go bout getting SFSymbols?

**Comment by rmccue** [comment]
Ah, forgot to document that. You need to download the [SF Symbols app](https://developer.apple.com/design/downloads/SF-Symbols.dmg), view package contents, and copy the TTF in the Resources directory into the repo.

We could automate this I think if we want?

**Comment by rmccue** [comment]
Updated; `yarn start` will now automatically download the icons for you.

**Comment by joehoyle** [comment]
Hmm I get:

```
tar -O -xzf "/tmp/sfsymbols/SF Symbols.pkg" "SFSymbols.pkg/Payload"
tar: Error opening archive: Unrecognized archive format
```

The file is there:

**Comment by rmccue** [comment]
Hmm, that archive error is annoying. Do you get it if you run the command manually?

**Comment by rmccue** [comment]
New post screen | On save | Published post
-- | -- | --
image | image | image

**Comment by joehoyle** [comment]
No, I had to install the app and manually copy it out

**Comment by rmccue** [comment]
Updated to use pkgutil rather than tar

**Pull request merged**
